plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
}

android {
    namespace = "com.framenest"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.framenest"
        minSdk = 26
        targetSdk = 36
        versionCode = 16
        versionName = "0.6.5-internal"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }

        // Never compile local NAS details into a distributable APK. The debug
        // spike accepts runtime input; these constants only preserve safe defaults.
        buildConfigField("String", "SMB_HOST", "\"\"")
        buildConfigField("int", "SMB_PORT", "445")
        buildConfigField("String", "SMB_USERNAME", "\"\"")
        buildConfigField("String", "SMB_PASSWORD", "\"\"")
        buildConfigField("String", "SMB_DOMAIN", "\"\"")
        buildConfigField("String", "SMB_SHARE", "\"\"")
        buildConfigField("String", "SMB_PATH", "\"/\"")
        buildConfigField("String", "SMB_TEST_FILE", "\"\"")
    }

    // Per-ABI APKs shrink install size (libVLC is the bulk).
    splits {
        abi {
            isEnable = true
            reset()
            include("arm64-v8a", "x86_64")
            isUniversalApk = true
        }
    }

    // Release keys are supplied by the maintainer/Actions, never generated by
    // the build. The publishing workflow also pins the owner-confirmed target certificate.
    signingConfigs {
        create("release") {
            providers.environmentVariable("ANDROID_KEYSTORE_PATH").orNull?.let {
                storeFile = file(it)
            }
            storePassword = providers.environmentVariable("ANDROID_STORE_PASSWORD").orNull
            keyAlias = providers.environmentVariable("ANDROID_KEY_ALIAS").orNull
            keyPassword = providers.environmentVariable("ANDROID_KEY_PASSWORD").orNull
        }
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
            // Keep the universal debug APK limited to the two supported ABIs.
            ndk {
                abiFilters += listOf("arm64-v8a", "x86_64")
            }
        }
        release {
            signingConfig = signingConfigs.getByName("release")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            // Match the split outputs; Play/App Bundle delivery still installs one ABI.
            ndk {
                abiFilters += listOf("arm64-v8a", "x86_64")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "META-INF/versions/9/previous-compilation-data.bin"
        }
    }

    sourceSets.getByName("androidTest").assets.directories.add("$projectDir/schemas")
}

// Fail closed for release packaging, while keeping ordinary debug CI usable
// without signing secrets. No unsigned release or fresh debug-key fallback.
val requireReleaseSigning = tasks.register("requireReleaseSigning") {
    group = "verification"
    description = "Require maintainer-supplied signing material before release builds."
    doLast {
        val required = listOf(
            "ANDROID_KEYSTORE_PATH", "ANDROID_STORE_PASSWORD", "ANDROID_KEY_ALIAS", "ANDROID_KEY_PASSWORD",
        )
        check(required.all { !providers.environmentVariable(it).orNull.isNullOrBlank() }) {
            "Release signing is not configured. See docs/RELEASING.md; refusing an unsigned release."
        }
        check(file(providers.environmentVariable("ANDROID_KEYSTORE_PATH").get()).isFile) {
            "The configured release keystore is missing."
        }
    }
}

tasks.matching {
    it.name in setOf(
        "preReleaseBuild", "validateSigningRelease", "packageRelease", "packageReleaseBundle", "signReleaseBundle",
    )
}.configureEach {
    dependsOn(requireReleaseSigning)
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.compose.material3.adaptive.navigation.suite)
    implementation(libs.androidx.compose.material3.window.size)
    implementation(libs.androidx.compose.material3.adaptive)
    implementation(libs.androidx.compose.material3.adaptive.layout)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)

    implementation(libs.libvlc.all)
    // Cover frames call libvlc_video_set_callbacks. The AAR supplies the
    // Android JNI dispatcher; vosk/sherpa must not also package com.sun.jna.
    implementation(libs.jna) {
        artifact {
            type = "aar"
        }
    }

    implementation(libs.smbj)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.coroutines.core)

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)
    implementation(libs.androidx.security.crypto)

    // FN-14: on-device listen-translate (Vosk ASR + ML Kit MT).
    implementation(libs.vosk.android) {
        exclude(group = "net.java.dev.jna", module = "jna")
    }
    // FN-51: SenseVoice-Small int8 ASR via sherpa-onnx (default engine).
    // AAR bundles the JNI bridge + onnxruntime natives for all ABIs; the
    // arm64-v8a/x86_64 abiFilters above keep only the two shipped ABIs.
    implementation(libs.sherpa.onnx) {
        exclude(group = "net.java.dev.jna", module = "jna")
    }
    implementation(libs.mlkit.translate)
    implementation(libs.kotlinx.coroutines.play.services)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)

    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.room.testing)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}
